version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: node build/index.js
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_PATH: http://backend:8000
    depends_on:
      - db
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: $POSTGRES_HOST
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - fastapi-piccolo-db:/var/lib/postgresql/data

volumes:
  fastapi-piccolo-db:

networks:
  default:
    name: fastapi-svelte-demo